# Generated by Django 6.0 on 2025-12-27 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_store', '0003_alter_user_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prod_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_type_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=50)),
                ('prod_brand', models.CharField(max_length=25)),
                ('prod_model', models.CharField(max_length=25)),
                ('prod_id_name', models.IntegerField(max_length=50)),
                ('prod_stock', models.IntegerField(default=0)),
                ('stock_date', models.DateTimeField(auto_now_add=True)),
                ('prod_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prod_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products_store.prod_type')),
            ],
        ),
    ]
