# Generated by Django 6.0 on 2025-12-28 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_store', '0004_prod_type_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_id_name',
            field=models.IntegerField(max_length=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_stock',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='products_store.prod_type'),
        ),
    ]
