# Generated by Django 6.0 on 2026-01-05 01:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_store', '0005_alter_product_prod_id_name_alter_product_prod_stock_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prod_type',
            new_name='Product_type',
        ),
        migrations.CreateModel(
            name='Product_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products_store.product')),
            ],
        ),
        migrations.CreateModel(
            name='Product_restock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restock', models.IntegerField()),
                ('stock_date', models.DateTimeField(auto_now_add=True)),
                ('prod_status', models.CharField(max_length=25)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products_store.product')),
            ],
        ),
        migrations.CreateModel(
            name='Product_stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('new_com', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products_store.product')),
            ],
        ),
    ]
