# Generated by Django 6.0 on 2026-01-15 18:47

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_store', '0008_alter_basket_user_alter_product_prod_id_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=1, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='product_pics/'),
            preserve_default=False,
        ),
    ]
