# Generated by Django 6.0 on 2026-01-20 11:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_store', '0011_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products_store.product_type'),
            preserve_default=False,
        ),
    ]
