# Generated by Django 6.0 on 2026-01-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_store', '0012_basket_order_date_alter_product_prod_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_type',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
