# Generated by Django 6.0 on 2026-01-24 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_store', '0013_product_type_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_stock',
            name='product',
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product_type',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Product_restock',
        ),
        migrations.DeleteModel(
            name='Product_stock',
        ),
    ]
