# Generated by Django 6.0 on 2026-01-29 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_store', '0014_remove_product_stock_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_subtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtype_name', models.CharField(max_length=25)),
                ('slug', models.SlugField(unique=True)),
                ('parent_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtypes', to='products_store.product_type')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='prod_subtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products_store.product_subtype'),
        ),
    ]
